<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mini_ERP.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="8.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mini-ERP.Domain\Mini-ERP.Domain\Mini-ERP.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Commands\MilkCollection\UpdateMilkCollection\" />
    <Folder Include="Features\Commands\MilkCollection\RemoveMilkCollection\" />
  </ItemGroup>

</Project>
